version: '2'

services:

  postgres:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    hostname: postgres
    ports:
    - 5432:5432
    environment:
    - DB_NAME=scraperdb
    - PG_PASSWORD=postgres

  flyway:
    image: boxfuse/flyway:5.2.4
    container_name: flyway
    hostname: flyway
    depends_on:
    - postgres
    volumes:
    - ./resources/db/migration/:/data
    - ./resources/db/migrate.sh:/migrate.sh
    environment:
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_NAME=scraperdb
    - DB_USER=postgres
    - DB_PWRD=postgres
    entrypoint: ["/bin/sh", "/migrate.sh"]
